apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  namespace: bookstore-app
  labels:
    app: bookstore-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookstore-backend
  template:
    metadata:
      labels:
        app: bookstore-backend
    spec:
      containers:
      - name: backend
        image: bprathap104/bookstore-backend:1.3
        env:
        - name: DB_HOST
          value: postgres-svc
        - name: DB_USER
          value: bookstore
        - name: DB_PASS
          value: bookstore123
        - name: DB_NAME
          value: bookstoredb
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: bookstore-app
spec:
  type: ClusterIP
  selector:
    app: bookstore-backend
  ports:
  - port: 5000
    targetPort: 5000
