apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bookorders.bookstore-app.io
spec:
  group: bookstore-app.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                customerName:
                  type: string
                bookTitle:
                  type: string
                quantity:
                  type: integer
                status:
                  type: string
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: bookorders
    singular: bookorder
    kind: BookOrder
    shortNames:
      - bo
