apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup-old-orders
  namespace: bookstore-app
spec:
  schedule: "0 2 * * *"  # Runs daily at 2 AM
  jobTemplate:
    spec:
      template:
        metadata:
          name: cleanup-old-orders
        spec:
          containers:
          - name: cleanup
            image: bprathap104/bookstore-backend:1.9
            env:
            - name: DB_HOST
              value: postgres-svc
            - name: DB_USER 
              value: bookstore
            - name: DB_PASS
              value: bookstore123
            - name: DB_NAME
              value: bookstoredb
            command: ["python", "cleanup_old_orders.py"]
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1