apiVersion: batch/v1
kind: CronJob
metadata:
  name: generate-sales-report
  namespace: bookstore-app
spec:
  schedule: "0 0 * * *" # runs daily at midnight
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: bookstore-backend
        spec:
          serviceAccountName: default
          containers:
            - name: sales-report
              image: bprathap104/bookstore-backend:1.9
              env:
                - name: DB_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: bookstore-config
                      key: db-host
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: db-secret
                      key: db-username
                - name: DB_PASS
                  valueFrom:
                    secretKeyRef:
                      name: db-secret
                      key: db-password
                - name: DB_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: bookstore-config
                      key: db-name
              command: ["python", "generate_sales_report.py"]
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
