apiVersion: batch/v1
kind: Job
metadata:
  name: cleanup-old-orders
  namespace: bookstore-app
spec:
  template:
    metadata:
      name: cleanup-old-orders
    spec:
      containers:
      - name: cleanup-orders
        image: bprathap104/bookstore-backend:1.9
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: bookstore-config
              key: db-host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-password
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: bookstore-config
              key: db-name
        command: ["python", "cleanup_old_orders.py"]
      restartPolicy: OnFailure
  backoffLimit: 4
  activeDeadlineSeconds: 200
