apiVersion: batch/v1
kind: Job
metadata:
  name: generate-sales-report
  namespace: bookstore-app
spec:
  template:
    metadata:
      name: generate-sales-report
    spec:
      containers:
      - name: sales-report
        image: bprathap104/bookstore-backend:1.9
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: bookstore-config
              key: db-host
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-password
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: bookstore-config
              key: db-name
        command: ["python", "generate_sales_report.py"]
      restartPolicy: OnFailure
  backoffLimit: 4
  activeDeadlineSeconds: 200